# Generated by Django 5.0.1 on 2024-02-01 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Blog_post', to='blog_app.blogpost'),
        ),
    ]
