# Generated by Django 5.0.1 on 2024-02-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blogpost_reviews_review_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='posts',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog_app.review'),
        ),
    ]
