# Generated by Django 5.0.1 on 2024-02-03 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_review_posts_blogpost_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog_app.blogpost'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
